language: java

jdk:
- oraclejdk8

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

script:
- "./gradlew test jacocoJunit5TestReport --console=plain"

after_success:
  - bash <(curl -s https://codecov.io/bash)
