language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-26.0.2

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

script:
- "./gradlew test jacocoJunit5TestReport --console=plain"

after_success:
  - bash <(curl -s https://codecov.io/bash)
